### ISSUE TITLE
Github Actions + Nginx + GCE VM + GoDaddy + SSL 部署多個 React、Next（PM2）專案〖全記錄〗

### ISSUE THREAD

**Issue by riverkuo** [riverkuo/blog#2]
# Github Actions + Nginx + GCE VM + GoDaddy + SSL 部署多個 React、Next（PM2）專案〖全記錄〗

<br />

                                _   _       _
                                | \ | | __ _(_)_ __ __  __
                                |  \| |/ _` | | '_ \\ \/ /
                                | |\  | (_| | | | | |>  <
                                |_| \_|\__, |_|_| |_/_/\_\
                                    |___/

<br />

## <ins>目錄</ins>

- [前言](#前言)
- [準備](#準備)
- [Nginx 是什麼](#nginx-是什麼)
- [操作](#操作)
  - [步驟 1-建立 Vm](#步驟1-建立-vm)
  - [步驟 2-安裝建立 Nginx](#步驟2-安裝建立-nginx)
  - [中場休息-Nginx 檔案架構與基礎設定觀念](#中場休息-nginx-檔案架構與基礎設定觀念)
  - [步驟 3-Nginx 設定](#步驟3-nginx-設定)
    - [綁定 Domain](#綁定-domain)
    - [綁定 SSL](#綁定-ssl)
    - [部署多個專案 1-設定 subdomain](部署多個專案1-設定subdomain)
    - [部署多個專案 2-設定 location](部署多個專案2-設定location)
  - [步驟 4-Github Actions 部署 React App](#步驟4-github-actions-部署-react-app)
  - [步驟 5-Github Actions 部署 Next App](#步驟5-github-actions-部署-next-app)
- [總結](#總結)
- [心得](#心得)
- [ref](#資料來源)

<br />

## <ins>前言</ins>

Hello 大家好～

最近萌生想要寫個 Side Project 的念頭，因此想到了部署的問題。剛好也想要自己玩看看 Nginx，於是就有了這篇文章。

主要想做的東西是：**把多個專案利用 Nginx 的 location 或 subdomain 的方式，部署到自己買的網域上**。

文章主要會帶著操作，穿插一些觀念或遇到的問題，希望可以幫助到大家！

<br />

## <ins>準備</ins>

- 1 個自己的 Domain（我在 [GoDaddy](https://www.godaddy.com/) 買的）
- 依照自己需求（SSL 憑證）（文章會教大家獲得免費 SSl 憑證的方法）
- github 上的 react app
- github 上的 next app

<br />

## <ins>Nginx 是什麼</ins>

:link: https://nginx.org/

> [!NOTE] 
> nginx ("engine x") is an HTTP web server, reverse proxy, content cache, load balancer, TCP/UDP proxy server, and mail proxy server. Originally written by Igor Sysoev and distributed under the 2-clause BSD License. Enterprise distributions, commercial support and training are available from F5, Inc.

Nginx 是一種 Web Server，當 Brower 發送請求時，Web Server 會尋找相對應的網頁資料，並把 response 丟回去給 Browser。除此之外，同時 Nginx 也提供 [反向代理（Reverse Proxy）](https://www.youtube.com/watch?v=4NB0NDtOwIQ)、[負載均衡（Load Balancer）](https://www.youtube.com/watch?v=RqfaTIWc3LQ)、快取...等功能。

其他常見的 Web Server: [Apache](https://httpd.apache.org/), [Cloudflare](https://www.cloudflare.com/)。

<br />

### <ins>步驟 1-建立 Vm</ins>

我這次是用 GCE Vm 來做，對應到 AWS EC2, Azure Virtual Machines，應該都大同小異，選一個自己習慣的操作就好了～

1. 進入 Google Cloud Console：`Compute Engine` -> `VM Instances` -> `Create Instance`
2. Machine Config：
   - OS and Storage -> `Ubuntu 22.04 LTS`（[Ｎ ginx 官網](https://nginx.org/en/linux_packages.html)有提供可以選的 OS）
   - Network -> `Allow HTTP traffic`, `Allow HTTPS traffic`
   - Region -> 選台灣 `asia-east1`
3. `Create the Instance`
4. 你就會獲得一個 Vm instance

在 Vm 的頁面，你會看到 `Internal IP`, `External IP` 和 `SSH`。
`SSH` 是連線進入 Vm 的方式（用 Google CLI 也可以），`External IP` 則是等一下要綁定 Domain 的方式。

> [!WARNING] 
> Vm 上的 IP 是暫時的，也就是今天 Vm 如果重啟了，IP 位置是會不一樣的。一般來說 IP 是會需要固定的，可以參考這一篇實作：[Create an instance that uses a static external IP address](https://cloud.google.com/compute/docs/ip-addresses/configure-static-external-ip-address#assign_new_instance)。
> 不過這是需要[付費](https://cloud.google.com/vpc/network-pricing)的哦~

</br>

### <ins>步驟 2-安裝建立 Nginx</ins>

接下來，我們要在這個 Vm 裡安裝 Nginx，這邊會使用到很多 Linux 指令：

- `sudo` -> substitute user(或 superuser) do
- `apt` -> advanced package tool
- `-y` -> assume "yes" as answer to all prompts and run non-interactively

1. 進入到 Vm 中
2. `sudo apt update && sudo apt upgrade -y` 更新 packages
3. `sudo apt install nginx -y ` 安裝 Nginx
4. `sudo nginx -v` 確認有安裝到

到這邊 Nginx 就已經裝上去了～不過我們還需將 Nginx run 起來

5. `sudo systemctl start nginx`
6. `sudo systemctl enable nginx`
7. `sudo systemctl status nginx` 確認 Nginx 的狀態：應為 `Active`

這個時候，造訪 external IP，就會看到 Nginx 的預設頁面 `Welcome to Nginx` 了～

<br/>

### <ins>中場休息-Nginx 檔案架構與基礎設定觀念</ins>

到這邊大概完成 1/3 了，稍微介紹一下 Nginx 的檔案配置和設定觀念。

<details>

<summary><i><text style="font-size:1.3rem"><ins>檔案架構</ins></text></i></summary>

<br/>

現在的資料夾會長這樣：

<br/>

            # nginx 設定位置

            etc/nginx/
            ├─ nginx.conf                    # 會拿 sites-enabled/*, conf.d/*
            ├─ conf.d/                       # 所有 sites config(not Debian based system)
            ├─ sites-available/              # 所有 sites config(Debian based system)(我們要編輯的地方)
            │  ├─ default
            ├─ sites-enabled/                # 所有 sites config symlink(Debaian based system)
            │  ├─ default

<br/>

            # 放靜態資源的地方(Debian based system)

            var/www/
            ├─ html/
            │  ├─ index.nginx-debian.html    # Nginx 建立的預設頁面 - Welcome to Nginx

<br/>

這個長相跟 Nginx 官網會有一點不同，原因是我們把 Nginx 架在 Ubuntu 上。像 `sites-available` 和 `sites-enabled` 就是 Ubuntu 才會有的資料夾，否則通常 sites config 會寫在 `conf.d` 裡。

靜態資源的資料夾 `var/www/` 就是放 build 起來的靜態網頁，這個路徑是專屬 Debian based system。

<br/>

> Symlink： 指向另一個檔案的檔案，Linux 系統支援。好處是可以輕鬆的做 version control, 或是針對 config enabled 或 disabled（同時不失去本身的檔案）。以 Nginx 為例： 需要將 `sites-available` 中的設定檔案建立symlink到 `sites-enabled` 中，才會啟用。若想要 disabled，只需要刪除 `sites-enabled` 中的檔案就好，同時不會失去真實的 config(在 `sites-available` 裡)。

<br/>

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>基礎設定觀念</ins></text></i></summary>

<br/>
接下來，我們來看看現在的預設設定檔

<br/>

> `sudo vim /etc/nginx/sites-available/default`

看到到東西大概長這樣(其實 Nginx 有把很多設定也都寫註解裡了)：

```
server {
        listen 80 default_server;                                 # IPv4 connections
        listen 80 default_server;                                 # IPv6 connections


        root /var/www/html;                                       # 尋找靜態檔案的資料夾

        index index.html index.htm index.nginx-debian.html;       # 從左到右尋找靜態檔案，有找到就回覆

        server_name _;                                            # 沒有相符的 domain name，就會進到這裡（通常和 default_server 一起使用）

        location / {                                              # 全部 location 都回覆 404
               try_files $uri $uri/ =404;
        }

}
```

這邊有一些重點：

1. `server` block 通常是依據 `server_name` 和 `listen` port 去區分
2. Nginx 則有一套規則(比對 `Ip Address` -> `port` -> `server_name`)去決定由哪個 `server` block 處理相對應的 request。
3. 決定由哪個 `server` block 後，會決定由哪個 `location` block 處理 request。優先度高到低為：
   <br/>

   ```
   a. Exact Match =
   b. Preferential Prefix ^~
   c. Regular Expression ~
   d. Prefix Match
   e. Default Location /
   ```

剩下的等接下實作再說哦～～

</details>

<br/>

### <ins>步驟 3-Nginx 設定</ins>

<details>

<summary><i><text style="font-size:1.3rem"><ins>綁定 Domain</ins></text></i></summary>

<br/>

首先，需要進到 GoDaddy 頁面

- 進入你購買的 Domain
- `DNS` -> `Add New Record` :link: [DNS 記錄](https://www.cloudflare.com/zh-tw/learning/dns/dns-records/#:~:text=%E4%BB%80%E9%BA%BC%E6%98%AFDNS%20%E8%A8%98%E9%8C%84%EF%BC%9F,%E4%BC%BA%E6%9C%8D%E5%99%A8%E5%9F%B7%E8%A1%8C%E4%BB%80%E9%BA%BC%E6%93%8D%E4%BD%9C%E3%80%82)
  - 選擇 `A` record
  - `value` 填 Vm Nginx external Ip
  - `Name` 填 `@` 或 `www`
- 這時，造訪 your-domain.com（要用 <mark>http</mark>），就會看到 Welcome to Nginx 的頁面～

<br/>

> 如果你發現 your-domain.com 一直被轉導到 https ，這是因為 chrome 有 cache 住原本 GoDaddy domain 的 https 紀錄，且會自動轉導過去。由於現在我們的 Nginx 沒有設定 SSL，所以會一直出現 Error CONNECTION FAIL。<br/> 可以先換瀏覽器（safari），或是把 chrome 設定 `Settings -> Privacy and Security -> Security-> Use Secure DNS` 關掉，清除快取後重開，就可以造訪 http 網站了。

<br/>

這時你可能會好奇，我們沒有在 Nginx 中指明 `server_name`，為什麼這樣可以被 Nginx handle 到？

還記得前面的 `sites-available/default` 檔嗎？

在 listen port 那邊有一個參數 `default_server`：Nginx 會檢查 request header "Host"，發現 your-domain.com 沒有符合任何一個 `server_name`，因此 Nginx 就會丟給 `default_server` 的 server block 去處理：

> - 一個 port 只能有一個 `default_server`。
> - 如果不指定 `default_server`，會由最 top 的 `server_block` 去處理。
> - 如果有很多個設定檔在 `sites-enabled` 中，最前面的檔案優先次序最高。

<br/>
<br/>

當然，建立一個新的 config 是比較推薦的做法：

- `sudo touch /etc/nginx/sites-available/your-domain.com.conf` 依據 Domain 名稱建立 config 檔
- `sudo vim /etc/nginx/sites-available/your-domain.com.conf` 編輯成下面的樣子

  ```
  server {
          listen 80;
          listen [::]:80;


          server_name your-domain.com;
          root /var/www/html/your-domain.com;
          index index.html;

          location / {
                  try_files $uri $uri/ =404;
          }
  }
  ```

- `sudo ln -s /etc/nginx/sites-available/ your-domain.com.conf /etc/nginx/sites-enabled/` 將這個檔案建立 symlink 到 `sites/enabled`

- `sudo echo "NGINX on your-domain.com!" | sudo tee /var/www/html/your-domain/index.html` 先建立相對應的 html 測試

- `sudo nginx -t` 測試 Nginx config -> 應為 successful
- `sudo systemctl restart nginx` 重啟 Nginx (只要有更動都需要重啟才會更新哦)

這時候，重新造訪 http://your-domain.com，就會得到 NGINX on your-domain.com! !!!

可喜可賀！接下來我們要來加上 SSL 憑證（免費），如果不需要就可以直接跳過至一步哦

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>綁定 SSL</ins></text></i></summary>

<br/>

我們要使用 [ZeroSSl](https://zerossl.com/) 來獲得免費的憑證（90 天，需要自己手動更新哦）

其實這著官網設定的就好，這邊簡單講一下：

- `獲得憑證後 -> 上傳到 Vm -> 移到想要的路徑 -> 設定 Domain config`

  ```
  server {
          listen 80;
          listen [::]:80;

          listen 443 ssl;                                                          # 新增 443 port
          listen [::]:443 ssl;                                                     # 新增 443 port

          ssl_certificate /etc/ssl/your-domain.com/certificate.crt;                # 指向憑證位置
          ssl_certificate_key /etc/ssl/your-domain.com/private.key;                # 指向 key 位置


          server_name your-domain.com;
          root /var/www/html/your-domain.com;
          index index.html;

          location / {
                  try_files $uri $uri/ =404;
          }
  }
  ```

- `sudo nginx -t`

- `sudo systemctl restart nginx`

這時造訪 https://your-domain.com，就會是通的啦～

> [Internet Assigned Numbers Authority](https://www.iana.org/) 在 1992 年發行的 [RFC1340](https://www.rfc-editor.org/rfc/rfc1340) 提到 port:80，在 1994 年發行的 [RFC1700](https://www.rfc-editor.org/rfc/rfc1700) 提到 port:443。

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>部署多個專案1-設定subdomain</ins></text></i></summary>

<br/>

subdomain(子網域)通常與主網域被視為不同的網站主體，適合應用在 不屬不同的服務上。

在網址的呈現上，會長這樣 `subdomain/your-domain.com`。

要如何在 GoDaddy 和 Nginx 上設置呢？

- 在 GoDaddy 中， `DNS` -> `Add New Record`

  - 選擇 `A` record
  - `value` 填 Vm Nginx external Ip
  - `Name` 填 想要的 subdomain name

- `sudo vim /etc/nginx/sites-available/your-domain.com.conf` 增加 subdomain 的 server block

  ```
  server {
          listen 80;
          listen [::]:80;


          server_name subdomain/your-domain.com;
          root /var/www/html/your-domain.com/subdomain;
          index index.html;

          location / {
                  try_files $uri $uri/ =404;
          }
  }
  ```

- `sudo echo "NGINX on subdomain/your-domain.com!" | sudo tee /var/www/html/your-domain/subdomain/index.html` 建立相對應的 html 測試

造訪 `subdomain/your-domain.com` 時，就會看到相對應的內容了！

然而，subdomain 畢竟是一個 domain，因此，雖然我們在 main domain 建立了 SSL 憑證，但是這邊 subdomain 會是沒有 SSL 的，他們是互不影響的東西！

想要讓 subdomain 有 SSL 憑證的話，有 2 種做法：

1. 再幫 subdomain 申請一個 SSL
2. main domain 的 SSL，改成用 Wildcard SSL 憑證(可以保護 main domain 和 所有 subdomain 的憑證，通常要花錢)

假如說，真的不想這麼麻煩的話，還有另外一種方式，也就是 部署在 location 上！！

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>部署多個專案2-設定location</ins></text></i></summary>

<br/>

location 通常使用在 和這個主網站有相關的服務上，但在這裡，我們使用 location 來部署不同的服務！

在網址的呈現上，會長這樣 `your-domain.com/your-location-site`。

- `sudo vim /etc/nginx/sites-available/your-domain.com.conf` 增加 location 的 block

  ```
  server {
          listen 80;
          listen [::]:80;


          server_name your-domain.com;
          root /var/www/html/your-domain.com;
          index index.html;

          location / {
                  try_files $uri $uri/ =404;
          }

          location /your-location-site {
                  alias /var/www/html/your-domain.com/your-location-site/;
                  index index.html;
                  try_files $uri $uri/ /your-location-site/index.html;
          }
  }
  ```

- `sudo echo "NGINX on your-domain.com/your-location-site!" | sudo tee /var/www/html/your-domain/your-location-site/index.html` 建立相對應的 html 測試

造訪 `your-domain.com/your-location-site` 時，就會看到相對應的內容了！

> 注意喔～這邊是我為了不要再設定 SSL 的做法，否則這個做法在正式環境實務上不常見！

</details>

<br/>

### <ins>步驟 4-Github Actions 部署 React App</ins>

<details>

<summary><i><text style="font-size:1.3rem"><ins>建立 workflows yml 檔</ins></text></i></summary>
<br/>

首先，要先在現有的 react 需要建立一個`.github/workflows/actions.yml`，裡面大概會長這樣：

```
name: Deploy

on:
  push:
    branches: [main]                                                       // 要部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4                                           // 選擇你要的 action

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Copy files to GCE VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"                                                  // build 完的檔案位置
          target: "/var/www/html/your-domain.com/your-location-site"        // 要放到 nginx 上的位置
          strip_components: 1                                               // 移除第一層目錄，否則會直接把 dist 丟進去

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:  sudo nginx -t && sudo systemctl reload nginx
```

這邊的 secrets 是在 github repo 裡的 secret，要記得去設定。
- NGINX_HOST：Vm 的 external IP
- NGINX_USER, SSH_PRIVATE_KEY：我是先在本地用 Google CLI 連線，然後把 private key 一整串複製上去，也要確定連線的 user。

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>設定 Nginx 資料夾與 user 權限</ins></text></i></summary>
<br/>

這時，如果嘗試部署的時候，會得到這樣的 error：
```
error:  tar: dist: Cannot mkdir: Permission denied
tar: dist/assets: Cannot mkdir: No such file or directory
tar: dist: Cannot mkdir: Permission denied
tar: dist/assets/index-D8b4DHJx.css: Cannot open: No such file or directory
tar: dist: Cannot mkdir: Permission denied
tar: dist/assets/index-DQV9j5a0.js: Cannot open: No such file or directory
tar: dist: Cannot mkdir: Permission denied
tar: dist/index.html: Cannot open: No such file or directory
tar: dist: Cannot mkdir: Permission denied
tar: dist/vite.svg: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
```

<br/>

原因就是，資料夾的與登入的 nginx user 權限不夠堆，於是 我們要再做一些設定：
- 在 nginx server 中
- `ls -ld /var/www/html/your-domain.com` 檢查資料夾的群組，得到"drwxr-xr-x 5 root root 4096"
- `sudo chgrp -R www-data /var/www/html/your-domain.com` 將資料夾與所有的子目錄和檔案加入 www-data 的群組
- `sudo chmod -R g+rwx /var/www/html/your-domain.com` 設定資料夾的權限 
  - r (read)-可以讀取目錄內容
  - w (write)-可以寫入/修改目錄內容
  - x (execute): 可以進入目錄
- `groups`：查看當前使用者的權限
- `sudo usermod -aG www-data {userName}` 將要使用的 user 加入 www-data 中
- `getent group www-data` 確認是否被加入（用 groups 檢查的話需要重新登入資料才會更新哦）

> 補充關於 www-data 的文章[[Day30]檔案權限, www-data,SUID, SGID, SBIT](https://ithelp.ithome.com.tw/articles/10228309)

</details>

<br/>

於是我們將 app 部署，就會成功了！！

(如果有其他問題，可以參考我的 repo 配置 => https://github.com/riverkuo/react18)

<br/>

### <ins>步驟 5-Github Actions 部署 Next App</ins>

由於 next14 是運行在 node.js 上，因此要 host 的時候一個 node.js sever。官方推薦的 self-host 方式是用 [docker](https://nextjs.org/docs/14/app/building-your-application/deploying#self-hosting)，而這篇文章要來使用 PM2。

#### <ins>PM2 是什麼</ins>

:link: https://pm2.keymetrics.io/

> PM2 是一個 Node.js 的進程管理器，可以讓 node 服務 crash 掉之後，自動重啟、多程序多服務，可提升處理 request 的速度...等等等。

<br/>

<details>

<summary><i><text style="font-size:1.3rem"><ins>安裝 PM2</ins></text></i></summary>
<br/>

- `sudo apt update`
- `sudo apt install nodejs npm`：安裝 Node.js
- `sudo npm install -g pm2`：安裝 PM2

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>Nginx 設定</ins></text></i></summary>
<br/>

進入 config 檔中

```
# 最上層新增一個 upstream
upstream your_upstream_name {
    server 127.0.0.1:3000;                      # 要監聽的 port number
}


server {
        listen 80;
        listen [::]:80;


        server_name your-domain.com;
        root /var/www/html/your-domain.com;
        index index.html;

        location / {
                try_files $uri $uri/ =404;
        }

        location /your-location-site {
                alias /var/www/html/your-domain.com/your-location-site/;
                index index.html;
                try_files $uri $uri/ /your-location-site/index.html;
        }

        # 新增一個 next 靜態資源路徑
        location ~ ^/([^/]+)/_next/static/(.*)$ {
    		        alias /var/www/server/$1/.next/static/$2;
	      }

        # 新增 next app 的 location，將 request 轉發到 upstream
        location /your-next-app {
                proxy_pass http://your_upstream_name;    
        }
  }

```

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>Next 設定</ins></text></i></summary>
<br/>

在 `next.config.js` 當中：

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  // 其他配置
  output: 'standalone' 
};

export default nextConfig;
```

[關於 `standalone`](https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files)

</details>

<details>

<summary><i><text style="font-size:1.3rem"><ins>建立 workflows yml 檔</ins></text></i></summary>
<br/>

```
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create deployment package                                              
        run: |
          mkdir -p deploy
          cp -r .next/standalone/.next deploy/             // standalone build 後的資料夾
          cp -r .next/standalone/package.json deploy/      // package.json
          cp -r .next/standalone/node_modules deploy/      // 生產環境依賴
          cp -r .next/static deploy/.next/                 // 靜態資源
          cp .next/standalone/server.js deploy/            // Next.js 服務器入口文件
          ls -la deploy/

      - name: Copy files to GCE VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/var/www/server/you-next-app"                                    // 要放到 nginx 上的位置(我這邊是放在 server 資料夾裡)
          strip_components: 1                                                       // 移除第一層目錄
          
      - name: Restart PM2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/server/you-next-app
            if pm2 list | grep -q "you-next-app"; then                               // 檢查若是 you-next-app 正在 running，先刪除後再重新 start
              pm2 delete you-next-app
            fi
            NODE_ENV=production PORT=3000 pm2 start server.js --name you-next-app    // port number 要是 nginx 設定的 upstream 的 port 哦
```

同樣要設定好 secrets 哦

</details>

<br/>

完成之後，我們將 app 部署，就會成功了！！

可以下指令 `pm2 status` ，會得到：

```
┌────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ your-next-app    │ default     │ 0.1.0   │ fork    │ you-pid  │ 88m    │ 0    │ online    │ 0%       │ 86.1mb   │ your-user│ disabled │
└────┴──────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

```

(如果有其他問題，可以參考我的 repo 配置 => https://github.com/riverkuo/next14)

<br/>

## <ins>總結</ins>

終於啦，這樣就完成這次的目的了，給有需要的人參考～

其實現在 Next 部署的方式很多，像是用 Vercel 還可以定義想要的 url，非常迅速也方便！

不過基於想要自己練習，所以還是手做了一次

我認為這次文章的難度對我來說比較高，尤其像比較系統方面的東西（例如系統本身的 folder structure），我簡直是一竅不通？！就剛好藉由這次的機會一起學習了，如果有錯誤也請不吝嗇地告訴我～

這次針對 Nginx, PM2 的用法其實也還沒有很完全，可以說是只把最基礎的設定走完而已，還有很多東西沒有玩到，有興趣的大家再自己研究了！

<br/>

## <ins>心得</ins>

我還記得剛開始用 cursor 的時候，最常使用的功能是 tab。最近很常的使用情境是叫它幫我找 reference、issues、documentation 的網址，雖然說自己 google 找說不定也不用花很多時間，但就是多了那一個動作，體感上真的有差！

軟體生態變化的很快，仍然有人會一直去優化現階段的流程、體驗、技術。雖然自己偶爾也會有被資訊轟炸的感覺冒出來ＸＤ，不過這也是這個產業的迷人之處吧！

小 Murmur：
這篇文章有很多的 reference 都是 cursor 找的，不過它有時很不穩定會一直丟給我壞掉的網址。本來想要寫在 cursor rules 裡說明：" 請丟網址給我之前先去 curl 看看 "，結果 cursor 在 curl 之前還需要手動同意，因此這解法就泡湯了～～

最後：
這次寫 markdown 發現 Alert 的功能
> [!NOTE] 
> Hello 我是 Alert ~~

視覺上看起來很舒服很喜歡，但是！居然不能放在 toggle 裡啊！！！！所以有一些地方改成 quote 了
我目前找不太到解法，就請大家的眼睛忍耐一下了

<br/>

## <ins>資料來源</ins>

- [Nginx](https://nginx.org/)
- [How To Install Nginx on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04)
- [Nginx in Ubuntu](https://help.ubuntu.com/community/Nginx)
- [Symlink](https://en.wikipedia.org/wiki/Symbolic_link#:~:text=In%20computing%2C%20a%20symbolic%20link,FreeBSD%2C%20Linux%2C%20and%20macOS.)
- [How nginx processes a request](https://nginx.org/en/docs/http/request_processing.html)
- [Nginx server 和 location 優先順序](https://bigpxuan.blogspot.com/2018/07/nginx-server-location.html)
- [NGINX 作為反向代理伺服器的規劃 / Building a Reverse Proxy with NGINX](https://blog.pulipuli.info/2023/04/blog-post_238.html)
- [Next.js 零停机部署记录：从 PM2 Cluster 到 Next Standalone 模式](https://www.elecmonkey.com/blog/blue-green-deploy)
- [PM2](https://pm2.keymetrics.io/)
