### ISSUE TITLE
Github Actions 部署推播通知到 Discord

### ISSUE THREAD

**Issue by riverkuo** [riverkuo/blog#4]
# Github Actions 部署推播通知到 Discord

<br />

    .__   __.   ______   .___________. __   _______  __    ______     ___   .___________. __    ______   .__   __.
    |  \ |  |  /  __  \  |           ||  | |   ____||  |  /      |   /   \  |           ||  |  /  __  \  |  \ |  |
    |   \|  | |  |  |  | `---|  |----`|  | |  |__   |  | |  ,----'  /  ^  \ `---|  |----`|  | |  |  |  | |   \|  |
    |  . `  | |  |  |  |     |  |     |  | |   __|  |  | |  |      /  /_\  \    |  |     |  | |  |  |  | |  . `  |
    |  |\   | |  `--'  |     |  |     |  | |  |     |  | |  `----./  _____  \   |  |     |  | |  `--'  | |  |\   |
    |__| \__|  \______/      |__|     |__| |__|     |__|  \______/__/     \__\  |__|     |__|  \______/  |__| \__|

<br />

## <ins>目錄</ins>

- [前言](#前言)
- [1. 取得 Discord webhook 並設定](#1.-取得-Discord-webhook-並設定)
- [2. 撰寫 action](#2.-撰寫-action)
- [3. 將 action 打包](#3.-將-action-打包)
- [心得](#心得)
- [資料來源](#資料來源)

<br />

## <ins>前言</ins>

繼上一次 [2025-05-17-Github Actions + Nginx + GCE VM + GoDaddy + SSL 部署多個 React、Next（PM2）專案〖全記錄〗](https://github.com/riverkuo/blog/issues/2)，我們已經成功將部署流程自動化了！

然而，上一次在部署的時候，都要到 Github 上等待最新的結果，好麻煩～

若是多人開發的話，要互相告知，也是非常瑣碎的事情

有沒有辦法讓部署結果自動發送通知呢？

想要完成這個功能有 2 個做法：

1. 複雜的做法 - 使用 Github Webhook（適合自己的伺服器或自動化平台、跨平台、跨雲端）
  - 在 deploy 時，建立一筆 deployment 記錄（可以透過透過 a.[Github Deployment API](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28)  或 b.[在 workflow 當中加入 environment 參數](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment#how-environments-relate-to-deployments)）
  - 在 Github -> Settings -> Webhook 中，增加 自己的伺服器 Webhook，並訂閱 deployment 相關的事件
  - 自己的伺服器再發送通知給 Discord Webhook

2. 簡單的做法 - 使用 Github Actions
  - 在部署的 workflow 中，監聽部署狀態並傳送通知給 Discord webhook

由於我沒有要再架一個自己的伺服器，於是會使用第二種做法~

<br />

## <ins>1. 取得 Discord webhook 並設定</ins>

- 在 Discord 當中：`Server Settings` -> `Integrations` -> `Create Webhook`

- 可以編輯 頭貼、名稱、要傳送 Webhook 的 discord 頻道

- 複製 Webhook 的 url，加到 Github Secret 當中（我是加在 Repository Secret，若是有根據環境不同的需求，可以放在 Deployment Secret 當中）

<br />

## <ins>2. 撰寫 action</ins>

我是在原本最後一個 step 後，再增加一個 step: Notify Discord

```
- name: Notify Discord
  if: always()
  env:                                                                           ## 建立要使用的變數們                 
    REPO_NAME: ${{ github.event.repository.name }}
    USER_NAME: ${{ github.actor }}
    BRANCH: ${{ github.ref_name }}
    ENVIRONMENT: {{your_environment}}                                            ## 你的環境(production、staging、dev)
    SHORT_SHA: ${{ github.sha }}
    FAILED_JOB: ${{ github.job }}
    DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}                      ## secrets 中的 DISCORD_WEBHOOK_URL
    RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    USER_URL: ${{ github.server_url }}/${{ github.actor }}
    REPO_URL: ${{ github.server_url }}/${{ github.repository }}
    COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
  run: |
    SHORT_SHA=${GITHUB_SHA:0:7}
    if [ "${{ job.status }}" = "success" ]; then
      curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"embeds\": [{\"title\": \"✅ Deploy Succeeded\", \"color\": 65280, \"author\": {\"name\": \"by ${USER_NAME}\", \"url\": \"${USER_URL}\"}, \"description\": \"[Deploy ${BRANCH} on ${ENVIRONMENT} - Click to view run](${RUN_URL})\", \"fields\": [{\"name\": \"Repo\", \"value\": \"[${REPO_NAME}](${REPO_URL})\", \"inline\": true}, {\"name\": \"Commit\", \"value\": \"[${SHORT_SHA}](${COMMIT_URL})\", \"inline\": true}], \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}]}" \
        "$DISCORD_WEBHOOK_URL"
    else
      curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"embeds\": [{\"title\": \"❌ Deploy Failed\", \"color\": 16711680, \"author\": {\"name\": \"by ${USER_NAME}\", \"url\": \"${USER_URL}\"}, \"description\": \"[Deploy ${BRANCH} on ${ENVIRONMENT} - Click to view run](${RUN_URL})\", \"fields\": [{\"name\": \"Repo\", \"value\": \"[${REPO_NAME}](${REPO_URL})\", \"inline\": true}, {\"name\": \"Commit\", \"value\": \"[${SHORT_SHA}](${COMMIT_URL})\", \"inline\": true}, {\"name\": \"Failed Job\", \"value\": \"${FAILED_JOB}\", \"inline\": true}], \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}]}" \
        "$DISCORD_WEBHOOK_URL"
    fi
```

<br/>

### ✅ 成功樣式 ✅
<img src="https://github.com/riverkuo/blog/blob/master/images/4_1.png?raw=true" width="500px">

<br />

### ❌ 失敗樣式 ❌
<img src="https://github.com/riverkuo/blog/blob/master/images/4_2.png?raw=true" width="500px">

<br/>
<br/>

找到有人做了一個 Discord Webhook 的 [visualizer](https://leovoel.github.io/embed-visualizer/)，給大家參考，可以自定義想要呈現的訊息格式

<br />

## <ins>3. 將 action 打包</ins>

當然，你會有很多專案都需要這個通知功能的時候，我們可以把這個 action 包成一個 package

1. 創建一個新的 repo
2. `git init`
3. 加一個 shell 檔案 `echo "echo Notify Discord" > notify-discord.sh`
4. 修改 shell 權限 `chmod +x notify-discord.sh`
5. 增加 action.yml 檔案：

    ```
    name: Notify Discord

    inputs:
      DISCORD_WEBHOOK_URL:          ## 要從外部傳入的參數
        description: 'Discord webhook URL'
        required: true

    runs:
      using: 'composite'
      steps:                       
        - name: Notify Discord      ## 基本上就是原本的 step 複製貼上
          shell: bash
          env:
            REPO_NAME: ${{ github.event.repository.name }}
            USER_NAME: ${{ github.actor }}
            BRANCH: ${{ github.ref_name }}
            ENVIRONMENT: production
            SHORT_SHA: ${{ github.sha }}
            FAILED_JOB: ${{ github.job }}
            DISCORD_WEBHOOK_URL: ${{ inputs.DISCORD_WEBHOOK_URL }}
            RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            USER_URL: ${{ github.server_url }}/${{ github.actor }}
            REPO_URL: ${{ github.server_url }}/${{ github.repository }}
            COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          run: |
              SHORT_SHA=${GITHUB_SHA:0:7}
              if [ "${{ job.status }}" = "success" ]; then
                curl -H "Content-Type: application/json" \
                  -X POST \
                  -d "{\"embeds\": [{\"title\": \"✅ Deploy Succeeded\", \"color\": 65280, \"author\": {\"name\": \"by ${USER_NAME}\", \"url\": \"${USER_URL}\"}, \"description\": \"[Deploy ${BRANCH} on ${ENVIRONMENT} - Click to view run](${RUN_URL})\", \"fields\": [{\"name\": \"Repo\", \"value\": \"[${REPO_NAME}](${REPO_URL})\", \"inline\": true}, {\"name\": \"Commit\", \"value\": \"[${SHORT_SHA}](${COMMIT_URL})\", \"inline\": true}], \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}]}" \
                  "$DISCORD_WEBHOOK_URL"
              else
                curl -H "Content-Type: application/json" \
                  -X POST \
                  -d "{\"embeds\": [{\"title\": \"❌ Deploy Failed\", \"color\": 16711680, \"author\": {\"name\": \"by ${USER_NAME}\", \"url\": \"${USER_URL}\"}, \"description\": \"[Deploy ${BRANCH} on ${ENVIRONMENT} - Click to view run](${RUN_URL})\", \"fields\": [{\"name\": \"Repo\", \"value\": \"[${REPO_NAME}](${REPO_URL})\", \"inline\": true}, {\"name\": \"Commit\", \"value\": \"[${SHORT_SHA}](${COMMIT_URL})\", \"inline\": true}, {\"name\": \"Failed Job\", \"value\": \"${FAILED_JOB}\", \"inline\": true}], \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}]}" \
                  "$DISCORD_WEBHOOK_URL"
              fi

        - name: Set GitHub Path       ## 指定 action 的路徑
          run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
          shell: bash
          env:
            GITHUB_ACTION_PATH: ${{ github.action_path }}

        - name: Run notify-discord.sh ## 執行 shell
          run: notify-discord.sh
          shell: bash
    ```

6. commit 過後，加上 version 的 tag

    ```
    git tag -a -m "Description of this release" v1
    git push --follow-tags
    ```

<br/>

這樣就大功告成啦

現在，你有任何專案通知 Discord 部署結果的時候，只要在 workflow 最後加上最後的 step

```
- name: Notify Discord
  uses: {你的 user 名稱}/{action repo 名稱}@{action 版本號}
  if: always()
  with:
    DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  ## 記得要去 secrets 加入參數
```

這樣專案們就都可以使用同一個通知 Discord 的功能了哦！！

- [我的 notify-discord-action](https://github.com/riverkuo/notify-discord-action)
- [我的 react 專案 workflow](https://github.com/riverkuo/react18/blob/main/.github/workflows/actions.yml)

<br />

## <ins>心得</ins>

這次看了很多 Github Actions 的文件，只能說 DevOps 真是博大精深，有非常多細節要注意！

後來查了一下，各種 CI/CD 工具（Jenkins, GitLab）也都可以整合不同的通訊軟體（Chat, Slack），也有很多現成包好的 action 可以用，就看各自的需求囉！

<br />

## <ins>資料來源</ins>

- [Discord Webhook 官方文件](https://discord.com/developers/docs/resources/webhook)
- [Github actions context 可以使用的參數](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs)
- [Github webhook events](https://docs.github.com/en/webhooks/webhook-events-and-payloads)
- [Github Managing environments for deployment](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment#how-environments-relate-to-deployments)
- [Github environment secrets](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization)
- [Github creating a composite actions](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action)
